routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('movie','MovieController');
Route::get('movie/destroy/{id}',['as'=>'movie/destroy','uses'=>'MovieController@destroy']);
Route::post('movie/show',['as'=>'movie/show','uses'=>'MovieController@show']);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
///////////////////////////////////////////////////////
Route::resource('category','CategoryController');
Route::post('category/show',['as'=>'category/show','uses'=>'CategoryController@show']);
Route::get('category/destroy/{id}',['as'=>'category/destroy','uses'=>'CategoryController@destroy']);

//////////////////////////////////////////////////////
Route::resource('state','StateController');
Route::post('state/show',['as'=>'state/show','uses'=>'StateController@show']);
Route::get('state/destroy/{id}',['as'=>'state/destroy','uses'=>'StateController@destroy']);

//////////////////////////////////////////////////////
Route::resource('user','UserController');
Route::post('user/show',['as'=>'user/show','uses'=>'UserController@show']);
Route::get('user/destroy/{id}',['as'=>'user/destroy','uses'=>'UserController@destroy']);

resources/views/movies/list.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-12">
				{!!Form::open(['route'=>'movie/show', 'method'=>'post','novalidate','class'=>'form-inline']) !!}
				<div class="form-group">
					<label>Name</label>
					<input type="text" class="form-control" name="name">
				</div>
				<div class="form-control">
					<button type="submit" class="btn btn-default">Search</button>
					<a href="{{ route('movie.index') }}" class="btn btn-primary">All</a>
					<a href="{{ route('movie.create') }}" class="btn btn-primary">Create</a>
				</div>
				{!! Form::close() !!}
			</article>
			<article class="col-md-12">
				<table class="table table-condensed table-striped table-bordered">
					<thead>
						<tr>
							<th>Name</th>
							<th>Description</th>
							<th>Usuario</th>
							<th>Categoria</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
						@foreach($movies as $movie)
						<tr>
							<td>{{ $movie->name }}</td>
							<td>{{ $movie->description}}</td>
							<td>{{ $movie->user->name}}</td>
							<td></td>
							<td>	
								<a class="btn btn-primary btn-xs" href="{{route('movie.edit',['id'=>$movie->id])}}">Edit</a>
								<a class="btn btn-danger btn-xs" href="{{route('movie/destroy',['id'=>$movie->id])}}">Delete</a>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</article>
		</div>
	</section>
@endsection

resources/views/movies/new.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!!Form::open(['route'=>'movie.store', 'method'=>'post','novalidate']) !!}
				<div class="form-group">
					<label>Nombre</label>
					<input type="text" name="name" class="form-control" required>
				</div>
				<div class="form-group">
					<label>Descripción</label>
					<input type="text" name="description" class="form-control" required>
				</div>
				<div class="form-group">
					<label>Categoria</label>
					<select id="category" >
						@foreach($categories as $category)
						<option value="{{$category->name}}">{{$category->name}}</option>
						@endforeach
					</select>
					<button type="button" onclick="agregar()">Agregar</button>
				</div>
				<div class="form-group">
					<button type="submit" class="btn btn-success"> Enviar</button> 
				</div>
				<input type="hidden" id="listCategories" name="listCategories[]">
				{!! Form::close() !!}
			</article>
			<script type="text/javascript">
				function agregar(){
					var category=document.getElementById('category').value;
					var categories= Array();
					var lista=document.getElementById('listCategories');

					categories.push(category);
					lista.append(category);
				}
			</script>
		</div>
	</section>
@endsection

resources/views/movies/update.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!!Form::model($movie,['route'=>['movie.update',$movie->id],'method'=>'put','novalidate'])!!}
				<div class="form-group">
					<label>Nombre</label>
					<input type="ext" name="name" class="form-control" required value="{{$movie->name}}">
				</div>
				<div class="form-group">
					<label>Descripción</label>
					<input type="text" name="description" class="form-control" required value="{{$movie->description}}">
				</div>
				<div class="form-group">
					<label>Estado</label>
					<input type="text" name="state_id" class="form-control" required value="{{$movie->state_id}}">
				</div>
				<div class="form-group">
					<button type="submit" class="btn btn-success">Enviar</button>
				</div>
				{!!Form::close() !!}
			</article>
		</div>
	</section>
@endsection