routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('movie','MovieController');
Route::get('movie/destroy/{id}',['as'=>'movie/destroy','uses'=>'MovieController@destroy']);
Route::post('movie/show',['as'=>'movie/show','uses'=>'MovieController@show']);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
///////////////////////////////////////////////////////
Route::resource('category','CategoryController');
Route::post('category/show',['as'=>'category/show','uses'=>'CategoryController@show']);
Route::get('category/destroy/{id}',['as'=>'category/destroy','uses'=>'CategoryController@destroy']);

//////////////////////////////////////////////////////
Route::resource('state','StateController');
Route::post('state/show',['as'=>'state/show','uses'=>'StateController@show']);
Route::get('state/destroy/{id}',['as'=>'state/destroy','uses'=>'StateController@destroy']);

//////////////////////////////////////////////////////
Route::resource('user','UserController');
Route::post('user/show',['as'=>'user/show','uses'=>'UserController@show']);
Route::get('user/destroy/{id}',['as'=>'user/destroy','uses'=>'UserController@destroy']);

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','rol','state_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function states(){
        return $this->hasMany('App\Models\State');
    }

    public function movie(){
        return $this->hasMany('App\Models\Movie');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User as User;
use App\Models\States as States;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users=User::all();
        return \View::make('users/listUser',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return \View::make('users/newUser',compact('users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $users=new User();
        $users->name=$request->name;
        $users->email=$request->email;
        $users->password=$request->password;
        dd($users->state_id=4);
        $users->save();
        return redirect('user');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        $users=User::where('name','like','%'.$request->name.'%')->get();
        return \View::make('users/listUser',compact('users'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $users=User::find($id);
        return \View::make('users/updateUser',compact('users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user=User::find($id);
        $user->name=$request->name;
        $user->state_id=$request->state_id;
        $user->save();
        return redirect('user');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $users=User::find($id);
        $users->delete();
        return redirect('user');
    }
}

resources/views/users/listUser.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!!Form::open(['route'=>'user/show','method'=>'post','novalidate','class'=>'form-inline'])!!}
				<div class="form-group">
					<label>Nombre</label>
					<input type="text" name="name" class="form-control">
				</div>
				<div class="form-group">
					<button type="submit" class="btn btn-default">Buscar</button>
					<a href="{{route('user.index')}}" class="btn btn-primary">Todos</a>
					<a href="{{route('user.create')}}" class="btn btn-primary">Crear</a>
				</div>
				{!!Form::close()!!}
			</article>
			<article class="col-md-10">
				<table class="table table-condensed table-striped table-bordered">
					<thead>
						<tr>
							<th>Nombre</th>
							<th>Estado</th>
						</tr>
					</thead>
					<tbody>
						@foreach($users as $user)
						<tr>
							<td>{{$user->name}}</td>
							<td>{{$user->state_id}}</td>
							<td>
								<a href="{{route('user.edit',['id'=>$user->id])}}" class="btn btn-primary xs">Editar</a>
								<a href="{{route('user/destroy',['id'=>$user->id])}}" class="btn btn-danger xs">Eliminar</a>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
			</article>
		</div>
	</section>
@endsection

resources/views/users/newUser.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!!Form::open(['route'=>'user.store','method'=>'post','novalidate'])!!}
					<div class="form-group">
						<label>Nombre</label>
						<input type="text" name="name" class="form-control">
					</div>
					<div class="form-group">
						<label>E-mail</label>
						<input type="email" name="email" class="form-control">
					</div>
					<div class="form-group">
						<label>Contraseña</label>
						<input type="password" name="password" class="form-control">
					</div>
					<div class="form-group">
						<button type="submit" class="btn btn-success">Registrar</button>
					</div>
				{!!Form::close()!!}	
			</article>
		</div>
	</section>
@endsection

resources/views/users/updateUser.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!!Form::model($users,['route'=>['user.update',$users->id],'method'=>'put','novalidate'])!!}
				<div class="form-group">
					<label>Nombre</label>
					<input type="text" name="name" required value="{{$users->name}}" class="form-control">
				</div>
				<div class="form-group">
					<label>Estado</label>
					<input type="text" name="state_id" required value="{{$users->state_id}}" class="form-control">
				</div>
				<div class="form-group">
					<button type="submit" class="btn btn-primary">Editar</button>
				</div>
				{!!Form::close()!!}
			</article>
		</div>
	</section>
@endsection