routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('movie','MovieController');
Route::get('movie/destroy/{id}',['as'=>'movie/destroy','uses'=>'MovieController@destroy']);
Route::post('movie/show',['as'=>'movie/show','uses'=>'MovieController@show']);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
///////////////////////////////////////////////////////
Route::resource('category','CategoryController');
Route::post('category/show',['as'=>'category/show','uses'=>'CategoryController@show']);
Route::get('category/destroy/{id}',['as'=>'category/destroy','uses'=>'CategoryController@destroy']);

//////////////////////////////////////////////////////
Route::resource('state','StateController');
Route::post('state/show',['as'=>'state/show','uses'=>'StateController@show']);
Route::get('state/destroy/{id}',['as'=>'state/destroy','uses'=>'StateController@destroy']);

//////////////////////////////////////////////////////
Route::resource('user','UserController');
Route::post('user/show',['as'=>'user/show','uses'=>'UserController@show']);
Route::get('user/destroy/{id}',['as'=>'user/destroy','uses'=>'UserController@destroy']);

app/Models/States.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class States extends Model
{
	public function user(){
		return $this->belongsTo('App\User');
	}

	public function movie(){
		return $this->belongsTo('App\Models\Movie');
	}

	public function categories(){
		return $this->belongsTo('App\Models\categories');
	}
}

app/Http/Controllers/StateController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\States as States;

class StateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $states = States::all();
        return \View::make('states/listStates',compact('states'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return \View::make('states/newState');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $states= new States();
        $states->state=$request->state;
        $states->save();
        return redirect('state');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        $states=States::where('state','like','%'.$request->state.'%')->get();
        return \View::make('states/listStates',compact('states'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $states=States::find($id);
        return \View::make('states/updateState',compact('states'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $states=States::find($id);
        $states->state=$request->state;
        $states->save();
        return redirect('state');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $states=States::find($id);
        $states->delete();
        return redirect()->back();
    }
}

resources/views/states/listStates.blade.php
@extends('layouts.app')
@section('content')
 <section class="container">
 	<div class="row">
 		<article class="col-md-12">
 			{!!Form::open(['route'=>'state/show', 'method'=>'post', 'novalidate', 'class'=>'form-inline'])!!}
 			<div class="form-group">
 				<label>Nombre</label>
 				<input type="text" name="name" class="form-control">
 			</div>
 			<div class="form-group">
 				<button type="submit" class="btn btn-default" >Buscar</button>
 				<a href="{{route('state.index')}}" class="btn btn-primary">Todos</a>
 				<a href="{{route('state.create')}}" class="btn btn-primary">Crear</a>
 			</div>
 			{!!Form::close()!!}
 		</article>
 		<article class="col-md-12">
 			<table class="table table-condensed table-striped table-bordered">
 				<thead>
 					<tr>
 						<th>Estado</th>
 					</tr>
 				</thead>
 				<tbody>
 					@foreach($states as $state)
 					<tr>
 						<td>{{$state->state}}</td>
 						<td>        
 							<a href="{{route('state.edit',['id'=>$state->id])}}" class="btn btn-primary xs">Editar</a>
 							<a href="{{route('state/destroy',['id'=>$state->id])}}" class="btn btn-danger xs">Eliminar</a>
 						</td>
 					</tr>
 					@endforeach
 				</tbody>
 			</table>
 		</article>
 	</div>
 </section>
@endsection

resources/views/states/newState.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!!Form::open(['route'=>'state.store','method'=>'post','novalidate'])!!}
				<div class="form-group">
					<label>Estado</label>
					<input type="text" name="state" class="form-control">
				</div>
				<div class="form-group">
					<button type="submit" class="btn btn-success" >Crear</button>
				</div>
				{!!Form::close()!!}
			</article>
		</div>
	</section>
@endsection

resources/views/states/updateState.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!!Form::model($states,['route'=>['state.update',$states->id],'method'=>'put','novalidate'])!!}
				<div class="form-group">
					<label>Estado</label>
					<input type="text" name="state" class="form-control" required value="{{$states->state}}">
				</div>
				<div class="form-group">
					<button type="submit" class="btn btn-success" >Editar</button>
				</div>
				{!!Form::close()!!}
			</article>
		</div>
	</section>
@endsection