routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('movie','MovieController');
Route::get('movie/destroy/{id}',['as'=>'movie/destroy','uses'=>'MovieController@destroy']);
Route::post('movie/show',['as'=>'movie/show','uses'=>'MovieController@show']);
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
///////////////////////////////////////////////////////
Route::resource('category','CategoryController');
Route::post('category/show',['as'=>'category/show','uses'=>'CategoryController@show']);
Route::get('category/destroy/{id}',['as'=>'category/destroy','uses'=>'CategoryController@destroy']);

//////////////////////////////////////////////////////
Route::resource('state','StateController');
Route::post('state/show',['as'=>'state/show','uses'=>'StateController@show']);
Route::get('state/destroy/{id}',['as'=>'state/destroy','uses'=>'StateController@destroy']);

//////////////////////////////////////////////////////
Route::resource('user','UserController');
Route::post('user/show',['as'=>'user/show','uses'=>'UserController@show']);
Route::get('user/destroy/{id}',['as'=>'user/destroy','uses'=>'UserController@destroy']);

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Categories as Categories;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories=Categories::all();
        return \View::make('categories/listCategories', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return \View::make('categories/newCategory');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $categories= new categories;
        $categories->name=$request->name;
        $categories->state_id=1;
        $categories->save();
        return redirect('category');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        $categories=Categories::where('name','like','%'.$request->name.'%')->get();
        return \View::make('categories/listCategories',compact('categories'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories=Categories::find($id);
        return \View::make('categories/updateCategory',compact('categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update($id,Request $request)
    {
        $categories=Categories::find($id);
        $categories->name=$request->name;
        $categories->state_id=$request->state_id;
        $categories->save();
        return redirect('category');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $categories= Categories::find($id);
        $categories->delete();
        return redirect()->back();
    }
}

resources/views/categories/listCategories.blade.php
@extends('layouts.app')
@section('content')

	<section class="container">
		<article class="col-md-12">
			{!!Form::open(['route'=>'category/show','method'=>'post','novalidate','class'=>'form-inline'])!!}
				<div class="form-group">
					<label>Nombre</label>
					<input type="text" class="form-control" name="name">
				</div>
				<div class="form-control">
					<button type="submit" class="btn btn-default">Buscar</button>
					<a href="{{ route('category.index') }}" class="btn btn-primary">Todas</a>
					<a href="{{ route('category.create') }}" class="btn btn-primary">Crear</a>
				</div>
			{!!Form::close()!!}
		</article>
		<article class="col-md-12">
			<table class="table table-condensed table-striped table-bordered">
				<thead>
					<tr>
						<th>Nombre</th>
						<th>Acción</th>
					</tr>
				</thead>
				<tbody>
					@foreach($categories as $category)
					<tr>
						<td>{{ $category->name}}</td>
						<td>
							<a class="btn btn-primary btn-xs" href="{{route('category.edit',['id'=>$category->id])}}">Editar</a>
							<a class="btn btn-danger btn-xs" href="{{route('category/destroy',['id'=>$category->id])}}">Eliminar</a>
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>
		</article>
	</section>
@endsection

resources/views/categories/newCategory.blade.php
@extends('layouts.app')
@section('content')
	
	<section class="container">
		<article>
			{!!Form::open(['route'=>'category.store','method'=>'post','novalidate'])!!}
			<div class="form-group">
				<label>Nombre de la categoria</label>
				<input type="text" name="name" class="form-control" required>
			</div>
			<div>
				<button type="submit" class="btn btn-success" >Registrar</button>
			</div>
			{!!Form::close()!!}
		</article>
	</section>

@endsection

resources/views/categories/updateCategory.blade.php
@extends('layouts.app')
@section('content')
	<section class="container">
		<div class="row">
			<article class="col-md-10 col-md-offset-1">
				{!!Form::model($categories,['route'=>['category.update',$categories->id],'method'=>'put','novalidate'])!!}
				<div class="form-group">
					<label>Nombre</label>
					<input type="text" name="name" class="form-control" required value="{{$categories->name}}">
				</div>
				<div class="form-group">
					<label>Estado</label>
					<input type="text" name="state_id" class="form-control" required value="{{$categories->state_id}}">
				</div>
				<div class="form-group">
					<button type="submit" class="btn btn-success" >Editar</button>
				</div>
				{!!Form::close()!!}
			</article>
		</div>
	</section>
@endsection